name: Test Governance
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  governance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup K3d
        uses: ./.github/actions/k3d

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@v1.0.0
        with:
          version: v0.33.0

      - name: Deploy the package in a connected environment
        run: zarf dev deploy

      - name: Check on the environment
        run: zarf tools kubectl get pods -A

      - name: Setup Lula
        uses: defenseunicorns/lula-action/setup@ab4323ae76627e708b9fb386f8a69743b8858e29
        with:
          version: v0.2.1

      - name: Perform Validation of OSCAL
        uses: defenseunicorns/lula-action/validate@ab4323ae76627e708b9fb386f8a69743b8858e29
        with:
          oscal-target: "oscal-component.yaml"
          threshold: "assessment-results.yaml"

      - uses: actions/upload-artifact@v4
        with:
          name: Assessment-Results
          path: assessment-results.yaml

      