name: Test Governance
on: pull_request

permissions:
  contents: read

jobs:
  governance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup K3d
        uses: ./.github/actions/k3d

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@v1.0.0
        with:
          version: v0.33.0

      - name: Deploy the package in a connected environment
        run: zarf dev deploy

      - name: Check on the environment
        run: zarf tools kubectl get pods -A

      